FROM python:3.10-slim

WORKDIR /app

# Copy all server logic
COPY server/ ./server/
COPY server/server_FedAsync.py .
COPY server/server_FedAvg.py .

# new change for using testset, I am using the client directory to access the train.py file
COPY ../client /app/client



# Dependencies
COPY server_requirements.txt .
RUN pip install --no-cache-dir -r server_requirements.txt

# This line dynamically runs the right server file
CMD ["sh", "-c", "python server_${SERVER_TYPE}.py"]
